default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: 123456

  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: to_do_list_development

test:
  <<: *default
  database: to_do_list_test

production:
  adapter: postgresql
  database: to_do_list_production
  username: postgres
  password: 123456
  host: localhost
  port: 5432

